name: Build and publish docker images
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: ansible-lint
            dockerfile: ansible-lint/Dockerfile
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Check for changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - ${{ matrix.image }}/**
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
      -
        name: Extract tag from Dockerfile
        id: extract-tag
        run: |
          tag=$(grep -oP '^#\s*TAG:\s*\K.*' ${{ matrix.dockerfile }} | tr -d '[:space:]')
          echo "Tag extracted from Dockerfile: $tag"
          echo "::set-output name=tag::$tag"
      -
        name: Build and push
        if: steps.changes.outputs.src == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.image }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/${{ matrix.image }}:${{ steps.extract-tag.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
